cache: npm

os:
  - osx
  - linux

osx_image:
  - xcode11

dist: bionic

language: node_js

node_js:
  - lts/dubnium
  - lts/erbium
  - 11
  - 12.13.0

addons:
  sonarcloud:
    organization: "nut-tree"
    token:
      secure: "mOHkKrMl0msR9mjlkW30vcJ4R9hBZQiTrdJYFE+Islq0WT/W49RKPJmxyDiHwlBvGH483cWIuA3rC95hMZwjn2c0ybQ+M1gzkB/QKAv1FFy21Ze6H7EhFRGJ9x4fKQA2kZL3IwSMEm4ABbL5ZpcdijC2iSsFbxMXBVYhe7rHNz+rSqCPVbQV/OKc/lZeMRJ62DL2Mx6KXciO5Xq3rKANFM1yie8QLG8DNhcUv0OVtp65RDcOG30uqBOA1qDfq9VOylVKabVJN4ta2THr46ocYY1YfnUUDpcPJHQwZSL7Gl7BwMnMgiDGqZbWasJpqdlJSy6TesJGu8SI4ETWGwTE4jnrH3uegPXGqIdxOtWXPVR90U2upZ7/ztVVmABEAQN0zW0kv3Gwx2XbJ/Db4qc7OTNz5i9uf2BQ/dDEmjX4rMPYKbKFONHknq+e5dZiJGhmwC7ns7qaTIH23QZV9xyvC1ymbgbogdu17/bNvjZaPFtpnnFm49X/VWrf7Lw+rrGL62c7DHfJrYNHiky5OsQmlqyBq7Sm3O6pqtREdeZbgSAYdbn6ADIXbP7luhlSfM0oZ+GuPv3vGqapr41YVE70vs33ehLUDiDqY5F0sKDXLp4vvucupx2YSOx1KJDxaXmfAZAnL3/RVzGFByyGOeF8TQLV29T4cdPcl0wpbJcpmgI="

services:
  - docker

before_install:
  - "bash ./.build/setup_${TRAVIS_OS_NAME}.sh"
install: true
script:
  - "bash ./.build/run_${TRAVIS_OS_NAME}.sh"

stages:
  - sonar
  - test
  - name: deploy
    if: (branch = develop) OR (tag IS present)

jobs:
  exclude:
    - stage: test
      node_js: 12.13.0
      os: linux
    - stage: test
      node_js: lts/erbium
      os: linux

  include:
    - stage: sonar
      os: linux
      dist: bionic
      node_js: lts/erbium
      after_success:
        - sonar-scanner
    - stage: deploy
      os: osx
      osx_image: xcode11
      language: node_js
      node_js: lts/erbium
      install: true
      script: true
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        - provider: script
          skip_cleanup: false
          script: bash ./.build/pre-release.sh
          on:
            branch: develop
        - provider: script
          skip_cleanup: false
          script: npm publish
          on:
            tags: true
